[package]
name = "dvn"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dvn"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "uln/idl-build"]

[dependencies]
anchor-lang = { version = "0.29.0", features = ["event-cpi"] }
worker-interface = { path = "../worker-interface", features = ["no-entrypoint"] }
pricefeed = { path = "../pricefeed", features = ["cpi"] }
utils = { path = "../../libs/utils" }
messagelib-helper = { path = "../../libs/messagelib-helper" }
uln = { path = "../uln", features = ["no-entrypoint"] }
solana-helper = "0.1.0"

[dev-dependencies]
secp256k1 = { version = "0.29.0", features = ["rand", "recovery"] }