[package]
name = "BlockedMessageLib"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
MessageLibCommon = { git = "https://github.com/LayerZero-Labs/LayerZero-v2.git", subdir = "packages/layerzero-v2/sui/contracts/message-libs/message-lib-common", rev = "sui-vm", override = true }

[addresses]
blocked_message_lib = "0x0"

[dev-dependencies]

[dev-addresses]
