[package]
name = "MultiCall"
version = "0.0.1"
edition = "2024.beta"
license = "MIT"

[dependencies]
Call = { local = "../call" }

[addresses]
multi_call = "0x0"

[dev-dependencies]


[dev-addresses]
