[package]
name = "endpoint"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "endpoint"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "messagelib-interface/idl-build"]

[dependencies]
anchor-lang = { version = "0.29.0", features = ["event-cpi"] }
solana-program = "=1.17.31"
solana-helper = "0.1.0"
cpi-helper = { path = "../../libs/cpi-helper" }
messagelib-interface = { path = "../messagelib-interface", features = ["cpi"] }
utils = { path = "../../libs/utils" }