[package]
name = "OFTComposerExample"
version = "0.0.1"
edition = "2024.beta"       # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
EndpointV2 = { local = "../../../../endpoint-v2" }
PtbMoveCall = { local = "../../../../ptb-builders/ptb-move-call" }
OFTCommon = { local = "../../oft-common" }
OApp = { local = "../../../oapp" }

[addresses]
oft_composer_example = "0x0"

[dev-dependencies]
OFT = { local = "../../oft" }
SimpleMessageLib = { local = "../../../../message-libs/simple-message-lib" }

[dev-addresses]
