[package]
name = "OFTCommon"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Call = { local = "../../../dynamic-call/call" }

[addresses]
oft_common = "0x0"

[dev-dependencies]

[dev-addresses]
