[package]
name = "DvnPtbBuilder"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Dvn = { local = "../../../workers/dvns/dvn" }
DvnFeeLib = { local = "../../../workers/dvns/dvn-fee-lib" }
PriceFeed = { local = "../../../workers/price-feed" }
Uln302PtbBuilder = { local = "../../../ptb-builders/msglib-ptb-builders/uln-302-ptb-builder" }

[addresses]
dvn_ptb_builder = "0x0"

[dev-dependencies]

[dev-addresses]