[package]
name = "LayerzeroViews"
version = "0.0.1"
edition = "2024.beta"
license = "MIT"

[dependencies]
Uln302 = { local = "../message-libs/uln-302" }

[addresses]
layerzero_views = "0x0"

[dev-dependencies]
Dvn = { local = "../workers/dvns/dvn" }
DvnFeeLib = { local = "../workers/dvns/dvn-fee-lib" }

[dev-addresses]