[package]
name = "price_feed_module_0"
version = "1.0.0"
authors = []

[addresses]
endpoint_v2 = "_"
price_feed_module_0 = "_"
endpoint_v2_common = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"

[dev-addresses]
endpoint_v2 = "0x12345678"
price_feed_module_0 = "0x65DD71"
endpoint_v2_common = "0x9098"
layerzero_admin = "0x18943124"
layerzero_treasury_admin = "0x1894312499"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/move-natives.git"
rev = "77d5f3e140143bdaa41f850115b3035c134193e3"
subdir = "initia_stdlib"

[dependencies]
endpoint_v2_common = { local = "../../../endpoint_v2_common" }
