use anchor_lang::prelude::error_code;

#[error_code]
pub enum UlnError {
    Unauthorized,
    InvalidAmount,
    InvalidExecutor,
    ZeroMessageSize,
    InvalidRequiredDVNCount,
    InvalidOptionalDVNCount,
    InvalidOptionalDVNThreshold,
    InvalidConfirmations,
    AtLeastOneDVN,
    Unsorted,
    InvalidTreasuryFeeCap,
    InvalidPacketVersion,
    InvalidEid,
    Verifying,
    InvalidWorkerId,
    InvalidOptionType,
    InvalidBps,
    ExceededMaxMessageSize,
    InvalidExecutorProgram,
    InvalidAccountLength,
    InvalidDvnProgram,
    InvalidDvn,
    LzTokenUnavailable,
    InsufficientFee,
    InvalidTreasury,
    InvalidLzTokenMint,
    InvalidConfigType,
    InvalidConfirmation,
    InvalidType1Size,
    InvalidType2Size,
    ExceededU128,
    NonSigner,
    InvalidPayer,
}
