[package]
name = "WorkerRegistry"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Call = { local = "../../dynamic-call/call" }

[addresses]
worker_registry = "0x0"

[dev-dependencies]

[dev-addresses] 