[package]
name = "executor"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "executor"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = [
    "anchor-lang/idl-build",
    "worker-interface/idl-build",
    "pricefeed/idl-build",
]

[dependencies]
anchor-lang = { workspace = true, features = ["event-cpi"] }
solana-helper = { workspace = true }
worker-interface = { workspace = true, features = ["no-entrypoint"] }
pricefeed = { workspace = true, features = ["cpi"] }
utils = { workspace = true }
oapp = { workspace = true }
