[package]
name = "endpoint-interface"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "endpoint_interface"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = ["cpi"]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["event-cpi"] }
solana-program = "2.3.0"
solana-helper = "0.1.0"
cpi-helper = { path = "../../libs/cpi-helper" }
utils = { path = "../../libs/utils" }
messagelib-interface = { path = "../messagelib-interface", features = ["cpi"] }