[package]
name = "ExecutorLayerZero"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Executor = { local = "../executor" }

[addresses]
executor_layerzero = "0x0"

[dev-dependencies]

[dev-addresses]
