[package]
name = "WorkerCommon"
version = "0.0.1"
edition = "2024.beta"


[dependencies]
Utils = { git = "https://github.com/LayerZero-Labs/LayerZero-v2.git", subdir = "packages/layerzero-v2/sui/contracts/utils", rev = "main" }
Call = { git = "https://github.com/LayerZero-Labs/LayerZero-v2.git", subdir = "packages/layerzero-v2/sui/contracts/call", rev = "main" }

[addresses]
worker_common = "0x0"

[dev-dependencies]

[dev-addresses] 