[toolchain]
channel = "nightly-2025-05-01"
# rustup install nightly
# channel = "nightly-2024-02-04" # if you want to expand the macro, you need to use nightly version
components = ["rustfmt", "clippy"]
