[package]
name = "executor"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "executor"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "worker-interface/idl-build", "pricefeed/idl-build"]

[dependencies]
anchor-lang = { version = "0.29.0", features = ["event-cpi"] }
solana-helper = "0.1.0"
worker-interface = { path = "../worker-interface", features = ["no-entrypoint"] }
pricefeed = { path = "../pricefeed", features = ["cpi"] }
utils = { path = "../../libs/utils" }
oapp = { path = "../../libs/oapp" }