[package]
name = "router_node_1"
version = "1.0.0"
authors = []

[addresses]
router_node_1 = "_"
endpoint_v2_common = "_"
endpoint_v2 = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"
msglib_types = "_"
worker_common = "_"

[dev-addresses]
router_node_1 = "0x9007"
endpoint_v2_common = "0x9098"
endpoint_v2 = "0x12345678"
layerzero_admin = "0x18943124"
layerzero_treasury_admin = "0x1894312499"
msglib_types = "0x521234"
worker_common = "0x3204817234"

[dependencies]
msglib_types = { local = "../../msglib_types" }
endpoint_v2_common = { local = "../../../endpoint_v2_common" }
worker_common = { local = "../../../worker_peripherals/worker_common" }