[package]
name = "uln"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "uln"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = [
    "anchor-spl/idl-build",
    "messagelib-helper/idl-build",
    "worker-interface/idl-build",
]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
primitive-types = { version = "0.12.1", default-features = false }
solana-helper = { workspace = true }
messagelib-helper = { workspace = true }
worker-interface = { workspace = true, features = ["cpi"] }
utils = { workspace = true }
