[package]
name = "uln"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "uln"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-spl/idl-build", "messagelib-helper/idl-build", "worker-interface/idl-build"]

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
primitive-types = { version = "0.12.1", default-features = false }
solana-helper = "0.1.0"
messagelib-helper = { path = "../../libs/messagelib-helper" }
worker-interface = { path = "../worker-interface", features = ["cpi"] }
utils = { path = "../../libs/utils" }
