[package]
name = "PtbMoveCall"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Utils = { git = "https://github.com/LayerZero-Labs/LayerZero-v2.git", subdir = "packages/layerzero-v2/sui/contracts/utils", rev = "main" }

[addresses]
ptb_move_call = "0x0"

[dev-dependencies]

[dev-addresses]
