[package]
name = "dvn"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dvn"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "uln/idl-build"]
custom-heap = []
custom-panic = []
anchor-debug = []

[dependencies]
anchor-lang = { workspace = true, features = ["event-cpi"] }
worker-interface = { workspace = true, features = ["no-entrypoint"] }
pricefeed = { workspace = true, features = ["cpi"] }
utils = { workspace = true }
messagelib-helper = { workspace = true }
uln = { workspace = true, features = ["no-entrypoint"] }
solana-helper = { workspace = true }

[dev-dependencies]
secp256k1 = { version = "0.29.0", features = ["rand", "recovery"] }
