[package]
name = "endpoint"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "endpoint"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "messagelib-interface/idl-build"]
custom-heap = []
custom-panic = []
anchor-debug = []

[dependencies]
anchor-lang = { workspace = true, features = ["event-cpi"] }
solana-program = { workspace = true }
solana-helper = { workspace = true }
cpi-helper = { workspace = true }
messagelib-interface = { workspace = true, features = ["cpi"] }
utils = { workspace = true }
