# Basic
hard_tabs = false
max_width = 100
use_small_heuristics = "Max"
# Imports
imports_granularity = "Preserve"
reorder_imports = true
# Consistency
newline_style = "Unix"
# Format comments
comment_width = 100
wrap_comments = true
# Misc
chain_width = 80
spaces_around_ranges = false
binop_separator = "Front"
reorder_impl_items = false
match_arm_leading_pipes = "Preserve"
match_arm_blocks = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true